package com.ojasvi.ecommerce.Enum;

public enum NotificationEvent {

    WELCOME,
    ACCOUNT_CREATED,
    ACCOUNT_VERIFIED,
    ACCOUNT_UPDATED,
    PASSWORD_CHANGED,
    PASSWORD_RESET,
    EMAIL_CHANGED,
    MOBILE_CHANGED,

    LOGIN_SUCCESS,
    LOGIN_FAILED,
    NEW_DEVICE_LOGIN,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    
    USER_BLOCKED,
    USER_UNBLOCKED,

    ORDER_PLACED,
    ORDER_CONFIRMED,
    ORDER_PROCESSING,
    ORDER_PACKED,
    ORDER_SHIPPED,
    OUT_FOR_DELIVERY,
    DELIVERED,
    ORDER_CANCELLED,
    ORDER_DELAYED,
    ORDER_COMPLETED,

    PAYMENT_PENDING,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED,

    RETURN_REQUESTED,
    RETURN_APPROVED,
    RETURN_REJECTED,
    PRODUCT_PICKUP_SCHEDULED,
    PRODUCT_PICKED_UP,
    REFUND_PENDING,
    REFUND_INITIATED,
    REFUND_COMPLETED,
    REFUND_FAILED,

    CART_REMINDER,
    WISHLIST_PRICE_DROP,
    PRODUCT_BACK_IN_STOCK,
    CART_ITEM_LOW_STOCK,

    PRODUCT_CREATED,
    PRODUCT_DELETED,
    PRODUCT_AVAILABLE,
    PRODUCT_DISCONTINUED,
    PRODUCT_UPDATED,

    COUPON_CREATED,
    COUPON_RECEIVED,
    COUPON_EXPIRING,
    COUPON_EXPIRED,
    OFFER,
    FLASH_SALE,
    FESTIVAL_OFFER,

    NEW_REVIEW_REPLY,
    REVIEW_REQUEST,
    REVIEW_APPROVED,
    REVIEW_REJECTED,

    SHIPPING_ADDRESS_UPDATED,
    DELIVERY_ATTEMPT_FAILED,

    NEW_ORDER,
    NEW_USER_REGISTERED,
    NEW_SELLER_REGISTERED,
    NEW_CONTACT_MESSAGE,
    NEW_REVIEW,
    NEW_RETURN_REQUEST,
    NEW_REFUND_REQUEST,

    LOW_STOCK,
    OUT_OF_STOCK,
    PRODUCT_RESTOCKED,
    INVENTORY_UPDATED,

    ORDER_ASSIGNED,
    ORDER_CANCELLED_BY_CUSTOMER,
    ORDER_CANCELLED_BY_ADMIN,

    PAYMENT_RECEIVED,
    PAYMENT_VERIFICATION_REQUIRED,

    SUPPORT_TICKET_CREATED,
    SUPPORT_TICKET_UPDATED,
    SUPPORT_TICKET_CLOSED,

    SYSTEM_MAINTENANCE,
    APPLICATION_UPDATE,
    GENERAL_ANNOUNCEMENT
}
